// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAcysoIMMT1Ed_cqyhWoEJtSvgMuRX9Mk',
    appId: '1:744340867632:web:d77d12ff491b5339f47bf5',
    messagingSenderId: '744340867632',
    projectId: 'cmbootstrapflutter',
    authDomain: 'cmbootstrapflutter.firebaseapp.com',
    databaseURL: 'https://cmbootstrapflutter-default-rtdb.firebaseio.com',
    storageBucket: 'cmbootstrapflutter.firebasestorage.app',
    measurementId: 'G-C2DR6DER6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrqbc8SrZDqCvS8p8BPy6i1ng9rBAfew',
    appId: '1:744340867632:android:70c4cb2393210a88f47bf5',
    messagingSenderId: '744340867632',
    projectId: 'cmbootstrapflutter',
    databaseURL: 'https://cmbootstrapflutter-default-rtdb.firebaseio.com',
    storageBucket: 'cmbootstrapflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVV8avIDsrY5Hr_XncY-tWlpVLGbIEFY8',
    appId: '1:744340867632:ios:6ed3b0637015d736f47bf5',
    messagingSenderId: '744340867632',
    projectId: 'cmbootstrapflutter',
    databaseURL: 'https://cmbootstrapflutter-default-rtdb.firebaseio.com',
    storageBucket: 'cmbootstrapflutter.firebasestorage.app',
    iosBundleId: 'com.example.cmBootstrapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVV8avIDsrY5Hr_XncY-tWlpVLGbIEFY8',
    appId: '1:744340867632:ios:6ed3b0637015d736f47bf5',
    messagingSenderId: '744340867632',
    projectId: 'cmbootstrapflutter',
    databaseURL: 'https://cmbootstrapflutter-default-rtdb.firebaseio.com',
    storageBucket: 'cmbootstrapflutter.firebasestorage.app',
    iosBundleId: 'com.example.cmBootstrapFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAcysoIMMT1Ed_cqyhWoEJtSvgMuRX9Mk',
    appId: '1:744340867632:web:a05031880ce04020f47bf5',
    messagingSenderId: '744340867632',
    projectId: 'cmbootstrapflutter',
    authDomain: 'cmbootstrapflutter.firebaseapp.com',
    databaseURL: 'https://cmbootstrapflutter-default-rtdb.firebaseio.com',
    storageBucket: 'cmbootstrapflutter.firebasestorage.app',
    measurementId: 'G-1QGHK21K0J',
  );
}
